{% set name = "magentropy" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/magentropy-{{ version }}.tar.gz
  sha256: f42ba1dcda99f9ee833461f5d4cf70274ee524b1dde7ba3a548131dca1b3c1cc

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - cycler >=0.11.0
    - matplotlib-base >=3.5.1
    - numba >=0.55.1
    - numpy >=1.21.5
    - pandas >=1.4.3, <2.0
    - pint >=0.19.2
    - pint-pandas >=0.2
    - python
    - scipy >=1.7.3

test:
  imports:
    - magentropy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/magentropy/
  summary: Perform magnetoentropic mapping of magnetic materials based on DC magnetization data.
  description: |
    MagentroPy provides a class, MagentroData, that can be used to calculate magnetocaloric
    quantities from DC magnetization data supplied as magnetic moment vs. temperature sweeps
    (monotonic) taken under several different magnetic fields. The class is set up to work
    out-of-the-box with .dat data files produced by a Quantum Design Vibrating Sample
    Magnetometer or a Quantum Design MPMS3 SQUID Magnetometer. However, pandas.DataFrames or
    delimited files such as .csv are also acceptable inputs.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sorenbear
